/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package avro.entities;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface proto {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"proto\",\"namespace\":\"avro.entities\",\"types\":[{\"type\":\"record\",\"name\":\"Employee\",\"fields\":[{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"active\",\"type\":\"boolean\",\"default\":true},{\"name\":\"salary\",\"type\":\"long\"}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends proto {
    public static final org.apache.avro.Protocol PROTOCOL = avro.entities.proto.PROTOCOL;
  }
}